# Generated by Django 4.0.1 on 2022-10-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FORMAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('des', models.TextField()),
                ('dur', models.IntegerField()),
                ('img', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
